USE [master]
GO

/****** Object:  Database [CLINICA]    Script Date: 05/02/2018 10:22:42 ******/
CREATE DATABASE [CLINICA] ON  PRIMARY 
( NAME = N'CLINICA', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL10.MSSQLSERVER\MSSQL\DATA\CLINICA.mdf' , SIZE = 2304KB , MAXSIZE = UNLIMITED, FILEGROWTH = 1024KB )
 LOG ON 
( NAME = N'CLINICA_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL10.MSSQLSERVER\MSSQL\DATA\CLINICA_log.LDF' , SIZE = 576KB , MAXSIZE = 2048GB , FILEGROWTH = 10%)
GO

ALTER DATABASE [CLINICA] SET COMPATIBILITY_LEVEL = 100
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [CLINICA].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [CLINICA] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [CLINICA] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [CLINICA] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [CLINICA] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [CLINICA] SET ARITHABORT OFF 
GO

ALTER DATABASE [CLINICA] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [CLINICA] SET AUTO_CREATE_STATISTICS ON 
GO

ALTER DATABASE [CLINICA] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [CLINICA] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [CLINICA] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [CLINICA] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [CLINICA] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [CLINICA] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [CLINICA] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [CLINICA] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [CLINICA] SET  ENABLE_BROKER 
GO

ALTER DATABASE [CLINICA] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [CLINICA] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [CLINICA] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [CLINICA] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [CLINICA] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [CLINICA] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [CLINICA] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [CLINICA] SET  READ_WRITE 
GO

ALTER DATABASE [CLINICA] SET RECOVERY FULL 
GO

ALTER DATABASE [CLINICA] SET  MULTI_USER 
GO

ALTER DATABASE [CLINICA] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [CLINICA] SET DB_CHAINING OFF 
GO

