CREATE DATABASE CLINICA
GO 
USE CLINICA
GO
CREATE TABLE TIPO_TEL (
ID int NOT NULL IDENTITY(1,1),
NOMBRE VARCHAR(40) NOT NULL,
PRIMARY KEY (ID)
);
GO
CREATE TABLE TELEFONO(
NUMERO INT NOT NULL,
TIPO INT NOT NULL,
PRIMARY KEY (NUMERO),
FOREIGN KEY (TIPO) REFERENCES TIPO_TEL(ID)
);
GO
CREATE TABLE PROVINCIA(
ID INT NOT NULL IDENTITY(1,1),
NOMBRE VARCHAR(30),
PRIMARY KEY (ID) 
);
GO
CREATE TABLE LOCALIDAD(
ID INT NOT NULL IDENTITY(1,1),
CP INT,
NOMBRE VARCHAR(50),
ID_PROVINCIA INT NOT NULL,
PRIMARY KEY (ID),
FOREIGN KEY (ID_PROVINCIA) REFERENCES PROVINCIA (ID)
);
GO
CREATE TABLE HORARIOS(
ID INT NOT NULL IDENTITY(1,1),
HORA_ABRE INT NOT NULL UNIQUE,
HORA_CIERRA INT NOT NULL UNIQUE,
HORA_CORTE INT,
HORA_CORTE_FIN INT,
CHECK(HORA_ABRE < HORA_CIERRA),
CHECK(HORA_CORTE < HORA_CORTE_FIN),
CHECK(HORA_ABRE < HORA_CORTE AND HORA_CIERRA > HORA_CORTE_FIN)
);
GO
CREATE TABLE DIAS(
ID INT NOT NULL IDENTITY(1,1),
NOMBRE VARCHAR(15),
PRIMARY KEY (ID)
);
--FALTA DIAS X HORARIO
GO
ALTER TABLE HORARIOS WITH CHECK ADD PRIMARY KEY(ID)
/*CREATE TABLE HORARIOS_DIAS(
ID_HORARIO INT NOT NULL UNIQUE,
ID_DIAS INT NOT NULL UNIQUE,
PRIMARY KEY CLUSTERED(
ID_HORARIO ASC,
ID_DIAS ASC
)
);*/
GO
CREATE TABLE CONSULTORIOS(
ID INT NOT NULL IDENTITY(1,1),
CALLE VARCHAR(40) NOT NULL UNIQUE,
ID_LOCALIDAD INT NOT NULL,
ID_HORARIO INT NOT NULL,
PRIMARY KEY (ID),
FOREIGN KEY (ID_LOCALIDAD) REFERENCES LOCALIDAD(ID),
FOREIGN KEY (ID_HORARIO) REFERENCES HORARIOS(ID)
);
GO
CREATE TABLE ESPECIALIDADES(
ID INT NOT NULL IDENTITY(1,1),
NOMBRE VARCHAR (30) NOT NULL UNIQUE,
PRIMARY KEY(ID)
);
GO
CREATE TABLE PROFESIONALES(
ID INT NOT NULL UNIQUE IDENTITY(1,1),
NOMBRE VARCHAR(40) NOT NULL,
APELLIDO VARCHAR (40) NOT NULL,
DNI INT UNIQUE NOT NULL,
ID_TEL INT NOT NULL UNIQUE,
CALLE VARCHAR (60), 
ID_LOCALIDAD INT,
ID_ESPECIALIDAD INT NOT NULL,
PRIMARY KEY(ID),
FOREIGN KEY(ID_TEL) REFERENCES TELEFONO(NUMERO),
FOREIGN KEY(ID_LOCALIDAD) REFERENCES LOCALIDAD(ID),
FOREIGN KEY(ID_ESPECIALIDAD) REFERENCES ESPECIALIDADES(ID)
);
GO
CREATE TABLE PACIENTES(
ID INT NOT NULL IDENTITY(1,1),
NOMBRE VARCHAR(60) NOT NULL,
APELLIDO VARCHAR(60) NOT NULL,
DNI INT NOT NULL UNIQUE,
ID_TEL INT NOT NULL,
CALLE VARCHAR(60),
ID_LOCALIDAD INT NOT NULL,
FECHA_NACIMIENTO DATE NOT NULL,
PRIMARY KEY (ID),
FOREIGN KEY (ID_TEL) REFERENCES TELEFONO(NUMERO),
FOREIGN KEY (ID_LOCALIDAD) REFERENCES LOCALIDAD(ID)
);
GO
CREATE TABLE INTERNACIONES(
ID INT NOT NULL IDENTITY(1,1),
ID_PACIENTE INT NOT NULL,
DIAGNOSTICO VARCHAR(200) NOT NULL,
OBSERVACION_ALTA VARCHAR(200),
ID_ESPECIALIDAD INT NOT NULL,
ID_DERIVADOR INT NOT NULL,
ENTRADA DATE NOT NULL,
SALIDA DATE,
PRIMARY KEY (ID),
FOREIGN KEY (ID_PACIENTE) REFERENCES PACIENTES(ID),
FOREIGN KEY (ID_ESPECIALIDAD) REFERENCES ESPECIALIDADES (ID),
FOREIGN KEY (ID_DERIVADOR) REFERENCES PROFESIONALES (ID)
);
GO
CREATE TABLE ATENCION(
ID INT NOT NULL IDENTITY(1,1),
FECHA DATE NOT NULL,
ID_PACIENTE INT NOT NULL,
ID_PROFESIONAL INT NOT NULL,
INDICACION VARCHAR(200) NOT NULL,
PRIMARY KEY (ID),
FOREIGN KEY (ID_PACIENTE) REFERENCES PACIENTES(ID),
FOREIGN KEY (ID_PROFESIONAL) REFERENCES PROFESIONALES (ID)
);
GO
CREATE TABLE COBERTURAS_MEDICAS(
ID INT NOT NULL IDENTITY(1,1), 
NOMBRE VARCHAR (40) NOT NULL UNIQUE,
PRIMARY KEY(ID)
);
GO 
CREATE TABLE PLANES(
ID INT NOT NULL IDENTITY(1,1),
NOMBRE VARCHAR (40) NOT NULL UNIQUE,
PRIMARY KEY (ID)
);
--FALTA PLANES X COBERTURAS_MEDICAS
GO
CREATE TABLE ESTADO(
ID INT NOT NULL IDENTITY(1,1),
NOMBRE VARCHAR(15),
PRIMARY KEY(ID)
);
GO
CREATE TABLE TURNOS(
ID INT NOT NULL IDENTITY(1,1),
ID_PACIENTE INT NOT NULL,
ID_ESTADO INT NOT NULL,
ID_PROFESIONAL INT NOT NULL,
FECHA_TURNO DATE NOT NULL,
FECHA_SOLICITUD DATE,
PRIMARY KEY (ID),
FOREIGN KEY (ID_PACIENTE) REFERENCES PACIENTES(ID),
FOREIGN KEY (ID_ESTADO) REFERENCES ESTADO(ID),
FOREIGN KEY (ID_PROFESIONAL) REFERENCES PROFESIONALES (ID)
);
GO 
ALTER TABLE PACIENTES
ADD ID_COBERTURA INT NOT NULL,
FOREIGN KEY(ID_COBERTURA) REFERENCES COBERTURAS_MEDICAS(ID)
GO
CREATE TABLE MAILS(
ID INT NOT NULL,
MAIL VARCHAR (70)NOT NULL,
PRIMARY KEY(ID)
);
GO
ALTER TABLE PACIENTES 
ADD ID_MAIL INT NOT NULL UNIQUE,
FOREIGN KEY (ID_MAIL) REFERENCES MAILS(ID)
GO
ALTER TABLE PROFESIONALES
ADD ID_MAIL INT NOT NULL UNIQUE,
FOREIGN KEY (ID_MAIL) REFERENCES MAILS(ID)
GO
